name: Laravel CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repo
      uses: actions/checkout@v3

    - name: Instalar PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2

    - name: Instalar dependencias
      run: composer install

    - name: Copiar .env
      run: cp .env.example .env

    - name: Generar key
      run: php artisan key:generate

    - name: Ejecutar tests
      run: php artisan test

    - name: Build Docker
      run: docker build -t inventario-app .

    - name: Deploy por SSH
      uses: appleboy/ssh-action@v0.1.6
      with:
      host: ${{ secrets.SERVER_IP }}
      username: root
      key: ${{ secrets.SSH_KEY }}
      script: |
        cd /var/www/inventario
        git pull
        docker-compose down
        docker-compose up -d --build

